spring:
  application:
    name: TryAngle
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tryangle
    url: jdbc:mysql://tryangle-db.c5ksqseqwssi.ap-northeast-2.rds.amazonaws.com:3306/tryangle

    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  mail:
    host: smtp.gmail.com
    port:  587
    username:  ${MAIL_USERNAME}
    password:  ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400
